apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-redis-depl
spec:
  selector:
    matchLabels:
      app: expiration-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: expiration-redis
    spec:
      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      containers:
        - name: expiration-redis
          image: redis # from docker hub
---
apiVersion: v1
kind: Service
metadata:
  name: expiration-redis-srv
spec:
  selector:
    app: expiration-redis
  ports:
    - name: db
      protocol: TCP
      port: 6379
      targetPort: 6379
