apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-mongo-depl
spec:
  selector:
    matchLabels:
      app: payments-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: payments-mongo
    spec:
      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      containers:
        - name: payments-mongo
          image: mongo:latest # from docker hub
---
apiVersion: v1
kind: Service
metadata:
  name: payments-mongo-srv
spec:
  selector:
    app: payments-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
